### ISSUE TITLE
Generation of data dictionary from UML XMI file fails with Metanorma 2.0.3

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-ogc#705]
Generation of a data dictionary from UML XMI file worked fine with Metanorma 2.0.0, but it now fails with Metanorma 2.0.3

You can reproduce the issue by running:

`docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/metanorma  metanorma compile --agree-to-terms -t ogc -x html document.adoc`

[on this document](https://github.com/opengeospatial/developer-events/blob/master/2024/Open-Standards-Code-Sprint/engineering-report/document.adoc)

Some of the fatal error message during compilation of a document.

```
/usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/xmi/parsers/xml.rb:51:in `serialize_to_hash': asciidoctor: FAILED: document.adoc: Failed to load AsciiDoc document - undefined method `name' for nil:NilClass (NoMethodError)

            name: model.name,
                       ^^^^^
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/xmi/parsers/xml.rb:40:in `parse'
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/xmi/parsers/xml.rb:32:in `parse'
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/parser.rb:47:in `block in parse_into_document'
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/parser.rb:47:in `map'
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/parser.rb:47:in `parse_into_document'
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/parser.rb:33:in `parse'
	from /usr/local/bundle/gems/lutaml-0.9.8/lib/lutaml/parser.rb:18:in `parse'
	from /usr/local/bundle/gems/metanorma-plugin-lutaml-0.7.1/lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb:62:in `lutaml_document_from_file_or_cache'
	from /usr/local/bundle/gems/metanorma-plugin-lutaml-0.7.1/lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb:89:in `process_text_blocks'
	from /usr/local/bundle/gems/metanorma-plugin-lutaml-0.7.1/lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb:78:in `block in processed_lines'
	from /usr/local/bundle/gems/metanorma-plugin-lutaml-0.7.1/lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb:77:in `loop'
	from /usr/local/bundle/gems/metanorma-plugin-lutaml-0.7.1/lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb:77:in `processed_lines'


```

Note that the Version details are below
```
Metanorma 2.0.3
Metanorma::Cli 1.10.5
Metanorma::Standoc 2.9.3/IsoDoc 2.11.0
Metanorma::ISO 2.8.2
Metanorma::Iec 2.5.0
Metanorma::IEEE 1.2.13
Metanorma::Ietf 3.3.9
Metanorma::Generic 2.6.5
Metanorma::BIPM 2.4.12
Metanorma::CC 2.4.12
Metanorma::Csa 2.4.12
Metanorma::IHO 1.0.0
Metanorma::JIS 0.3.1
Metanorma::UN 0.12.15
Metanorma::Ogc 2.5.14
Metanorma::ITU 2.5.0

```

**Comment by ghobona** [comment]
Note that the page that imports the XMI file is [here](https://github.com/opengeospatial/developer-events/blob/master/2024/Open-Standards-Code-Sprint/engineering-report/sections/annex-a.adoc).

**Comment by ronaldtse** [comment]
Thank you @ghobona for reporting. 

@kwkwan could you please help fix this? Thanks.

**Comment by kwkwan** [comment]
Hi @ghobona and @ronaldtse, this issue is related to https://github.com/lutaml/lutaml/issues/82.  Please update lutaml to v0.9.9 to fix it.

**Comment by ghobona** [comment]
We generally use metanorma through docker. I presume that means that metanorma-docker has to be updated to lutaml to v0.9.9.

**Comment by opoudjis** [comment]
Should have gone live yesterday. We are publishing notifications of docker updates on https://github.com/orgs/metanorma/discussions/6#discussioncomment-10391608

**Comment by ghobona** [comment]
The functionality appears to be working fine with the latest version of metanorma (version 2.0.4).

https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcna-auto-review/blob/main/24-034.html#_example_use_of_model_driven_standards_with_ogc_api_common

This GitHub Issue can be closed.
